### ISSUE TITLE
Comparison with dlkcat results

### ISSUE THREAD

**Issue by jiejiangtao** [HanselYu/PreKcat#4]
Hi
the average coefficient of determination (R2) value on the test set from five rounds of random splitting was 0.68。  Is the test set here 10 of the total data set。 The results of your test set are very good, I wonder if the code could be available.

**Comment by HanselYu** [comment]
Thansks for your attention!
We have released a new version of PreKcat, the code is as follow:
https://github.com/Luo-SynBioLab/UniKP
I hope this may be helpful.
